name: dart_lcs_client
description: The Official dart client for the HackRU back end
version: 1.0.9
author: HackRU RnD Flutter Team <rnd@hackru.org>
homepage: https://github.com/HackRU/dart-lcs-client

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"
  flutter: ">=1.2.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.11.3+16
#  http: ^0.12.0+2
  flutter_linkify: ^2.1.0
#  url_launcher: ^5.1.2
  url_launcher: ^4.1.0+1
  equatable: ^0.4.0
  meta: ^1.1.6
  http_middleware: ^1.0.0
  intl: ^0.15.8
#  path_provider: ^1.2.0
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter